
generos([drama,romance,comedia,misterio,suspenso,comediaRomantica,musical,horror,accion,crimen,ciencia_ficcion,aventura,fantasia]).

pelicula(boogieNights1997).
pelicula(fruitvaleStation).
pelicula(malcomYMarie).
pelicula(ladyBird).
pelicula(fractura).
pelicula(silverLiningsPlaybook).
pelicula(yessGood).
pelicula(siSupieras).
pelicula(laMadreDelBlues).
pelicula(unobr).
pelicula(the_karate_kid).
pelicula(midnight_run).
pelicula(the_imposible).
pelicula(the_terminal).
pelicula(army_of_the_dead).
pelicula(total_recall).
pelicula(el_laberinto_del_fauno).
pelicula(the_disaster_artist).
pelicula(supercool).
pelicula(nightcrawler).
pelicula(busca_dela_felicidad).
pelicula(braveheart).
pelicula(braveheart).
pelicula(hombres_de_honor).
pelicula(lawrenceArabia).
pelicula(teoria_del_todo).
pelicula(patchAdams).
pelicula(lobo_de_wallStreet).
pelicula(chicaDanesa).
pelicula(figurasOcultas).
pelicula(elIrlandes).
pelicula(entrenadorCarter).
pelicula(metropolis).
pelicula(spaceJam).
pelicula(purgaInfinita).
pelicula(viudaNegra).
pelicula(guerra_del_manana).
pelicula(luca).
pelicula(tiempo).
pelicula(cruella).

director(boogieNights1997,paulThomasAnderson).
director(fruitvaleStation,ryanCoogler).
director(malcomYMarie,samLevinson).
director(ladyBird,gretaGerwing).
director(fractura,bradAnderson).
director(silverLiningsPlaybook,davidORussel).
director(yessGood,karenMaine).
director(siSupieras,aliceWu).
director(laMadreDelBlues,georgeCWolfe).
director(unobr,davidMarmor).
director(the_karate_kid,john_g_avildsen).
director(midnight_run,martin_brest).
director(the_imposible,juan_antonio_bayona).
director(the_terminal,steven_spielberg).
director(army_of_the_dead,zack_snyder).
director(total_recall,paul_verhoeven).
director(el_laberinto_del_fauno,guillermo_del_toro).
director(the_disaster_artist, james_franco).
director(supercool,greg_mottola).
director(nightcrawler, dan_gilroy).
director(busca_dela_felicidad,gabriele_Muccino).
director(braveheart,melGibson).
director(braveheart,melGibson).
director(hombres_de_honor,georgeTillman).
director(lawrenceArabia,davidLean).
director(toria_del_todo,jamesMarsh).
director(patchAdams,tomShadyac).
director(lobo_de_wallStreet,martinScorsese).
director(chicaDanesa,tomHooper).
director(figurasOcultas,theodoreMelfi).
director(elIrlandes,martinScorsese).
director(entrenadorCarter,thomasCarter).
director(metropolis,fritzLang).
director(spaceJam,malcolmD).
director(purgaInfinita,everardoGout).
director(viudaNegra,cateShortlan).
director(guerra_del_manana,chrisMcKay).
director(luca,enricoCasarosa).
director(tiempo,nightShyamalan).
director(cruella,craigGillespie).


genero(boogieNights1997,[drama]).
genero(fruitvaleStation,[drama]).
genero(malcomyMarie,[drama,romance]).
genero(ladyBird,[drama,comedia]).
genero(fractura,[suspenso,misterio]).
genero(silverLiningsPlaybook,[drama,comediaRomantica]).
genero(yessGood,[comedia]).
genero(siSupieras,[comedia,drama,romance]).
genero(laMadreDelBlues,[drama,musical]).
genero(unobr,[drama,horror,suspenso]).
genero(the_karate_kid,[drama,accion]).
genero(midnight_run,[comedia,accion]).
genero(the_imposible,[drama]).
genero(the_terminal,[comedia,drama]).
genero(army_of_the_dead,[accion,crimen,horror]).
genero(total_recall,[ciencia_ficcion,aventura]).
genero(el_laberinto_del_fauno,[drama,fantasia]).
genero(the_disaster_artist,[comedia,drama]).
genero(supercool,[comedia]).
genero(nightcrawler,[misterio,drama]).
genero(busca_dela_felicidad,[drama]).
genero(braveheart,[drama]).
genero(braveheart,[drama]).
genero(hombres_de_honor,[drama]).
genero(lawrenceArabia,[aventura]).
genero(teoria_del_todo,[drama]).
genero(patchAdams,[drama,comedia]).
genero(lobo_de_wallStreet,[drama]).
genero(chicaDanesa,[drama]).
genero(figurasOcultas,[drama]).
genero(elIrlandes,[suspenso]).
genero(entrenadorCarter,[comedia,drama]).
genero(metropolis,[drama]).
genero(spaceJam,[comedia]).
genero(purgaInfinita,[suspenso,accion]).
genero(viudaNegra,[accion,aventura]).
genero(guerra_del_manana,[suspenso,accion]).
genero(luca,[comedia]).
genero(tiempo,[suspenso]).
genero(cruella,[comedia,drama]).

recomienda(Pelicula, Genero) :- genero(Pelicula, Y) , member(Genero,Y).
directores(X) :- director(_,X).


